# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.1-alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: simp_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Run migrations
      run: |
        export PATH=$PATH:/usr/local/go/bin
        goose postgres postgresql://postgres:password@localhost:5432/simp_bank up

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
      id: go

    - name: Test
      run: go test -v -cover ./...
